/*
 * sendRulesIpTablesMain.c
 *
 *  Created on: Jul 10, 2014
 *      Author: secnok
 */

#include <unistd.h>
#include <sys/types.h>
#include <stdio.h>
#include <string.h>

	int rulesINPUT=0;
	int rulesFORDWARD=0;
	int rulesOUTPUT=0;
void parsingLineSendTules(char line[100]){



	// if the line begin with "Chain INPUT"
	if ((line[0]=='C') && (line[1]=='h') && (line[2]=='a')&& (line[3]=='i')&&(line[4]=='n')&&(line[5]==' ')){
		if ((line[6]=='I')&&(line[7]=='N')&&(line[8]=='P')&&(line[9]=='U')&&(line[10]=='T')){
			printf("Rules configured in INPUT Chain\n");
			rulesINPUT=1;
		}
		if ((line[6]=='F')&&(line[7]=='O')&&(line[8]=='R')&&(line[9]=='W')&&(line[10]=='A')&&(line[11]=='R')&&(line[12]=='D')){
			printf("\n");
			printf("Rules configured in FORDWARD Chain\n");
			rulesFORDWARD=1;
			rulesINPUT=0;

		}
		if ((line[6]=='O')&&(line[7]=='U')&&(line[8]=='T')&&(line[9]=='P')&&(line[10]=='U')&&(line[11]=='T')){
			printf("\n");
			printf("Rules configured in OUTPUT Chain\n");
			rulesOUTPUT=1;
			rulesINPUT=0;
			rulesFORDWARD=0;
		}

	}else if ((line[0]=='t') && (line[1]=='a') && (line[2]=='r')&& (line[3]=='g')&&(line[4]=='e')&&(line[5]=='t')){ // Ignore case
					// do nothing

	}else{
		// show input rules
		if ((rulesINPUT==1) && (strlen(line)!=5)){
			printf("Rule INPUT--> %s", line);
		}
		// if there is not input rules configured
		if ((rulesINPUT==1)&&(strlen(line)==5)){
			printf("No INPUT rules configured\n");
		}
		// show FORWARD rules
		if ((rulesFORDWARD==1) && (strlen(line)!=5)){
			printf("Rule FORDWARD--> %s", line);
		}
		// if there is not FORDWARD rules configured
		if ((rulesFORDWARD==1)&&(strlen(line)==5)){
			printf("No FORDWARD rules configured\n");
		}
		// show output rules
		if ((rulesOUTPUT==1) && (strlen(line)!=5)){
			printf("Rule OUTPUT--> %s", line);
		}
		// if there is not OUTPUT rules configured
		if ((rulesOUTPUT==1)&&(strlen(line)==5)){
			printf("No OUTPUT rules configured\n");
		}
		//if (strlen(line)==5){
			// do nothing);
		//}
	}
}


void sendRulesConfiguredInIpTables(){
	char line[100];
	FILE *fp;

	/* Run command to get rules configured in iptables */
	fp = popen("iptables -L -n | awk '{printf $1\" \"$2\" \"$4\" \"$5\" \"$6\"\\n\"}' ", "r");

	/* Error open file */
	if (fp== NULL){
		printf("Failed to run command \n");
	}else{
		/* Read the output generated by the command */
		while (fgets(line,sizeof(line), fp) != NULL ){
			if (strlen(line)!=5){
				parsingLineSendTules(line);
			}
		}

	}
}




int main(int argc, char *argv[]) {

	printf("we are going to get the rules configured into iptables \n\n");
	sendRulesConfiguredInIpTables();

	return 0;
}
